apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jurisai-staging

namespace: jurisai

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: jurisai-web
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- target:
    kind: Deployment
    name: jurisai-ws
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
- target:
    kind: Deployment
    name: jurisai-worker
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

images:
- name: ${DOCKER_REGISTRY}/jurisai-web
  newName: gcr.io/jurisai-staging/jurisai-web
- name: ${DOCKER_REGISTRY}/jurisai-ws
  newName: gcr.io/jurisai-staging/jurisai-ws
- name: ${DOCKER_REGISTRY}/jurisai-worker
  newName: gcr.io/jurisai-staging/jurisai-worker
